FROM tonglil/auth-gcloud:466.0.0-slim

RUN apt-get update && apt-get install kubectl

ENV CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=false

COPY auth-gke.sh /bin/auth-gke

ENTRYPOINT ["/bin/auth-gke"]
