name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        version: [latest, alpine, slim]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push ${{ matrix.version }}
      uses: docker/build-push-action@v4
      with:
        push: true
        file: Dockerfile.${{ matrix.version }}
        tags: ${{ github.repository }}:${{ matrix.version }}
        platforms: linux/amd64,linux/arm64,linux/arm
